### ISSUE TITLE
Ajouter un gitignore au projet

### ISSUE THREAD

**Issue by Ankhas** [O4h/movies-api#4]
Afin d'éviter de push des fichiers résiduels comme : 
- le dossier .idea
- les dossiers __pycache__ 
- etc

on peut créer un fichier gitignore que git va aller consulter pour les enlever de son analyse et de sa reconnaissance de fichier.

Plus d'infos ici : 
- https://www.atlassian.com/fr/git/tutorials/saving-changes/gitignore
- https://git-scm.com/docs/gitignore

Pour information, en général on trouve tout son bonheur ici : https://github.com/github/gitignore/blob/main/Python.gitignore (ce projet recense un gitignore très général pour pleins de langages/outils de programmation, à mettre en favoris sur Github ;) )

**Comment by O4h** [comment]
#7
